// riscv_zynq_bridge.v
// Plain Verilog-2001 wrapper to allow SystemVerilog module in Vivado Block Design

module riscv_zynq_bridge #(
    parameter ADDR_WIDTH = 10,
    parameter AXI_ADDR_WIDTH = 32,
    parameter AXI_DATA_WIDTH = 32,
    parameter C_S_AXI_DATA_WIDTH = 32,
    parameter C_S_AXI_ADDR_WIDTH = 4
) (
    input  wire        clk,
    input  wire        aresetn,

    // AXI-Lite
    input  wire [C_S_AXI_ADDR_WIDTH-1:0] s_axi_ctrl_awaddr,
    input  wire [2:0]                    s_axi_ctrl_awprot,
    input  wire                          s_axi_ctrl_awvalid,
    output wire                          s_axi_ctrl_awready,
    input  wire [C_S_AXI_DATA_WIDTH-1:0] s_axi_ctrl_wdata,
    input  wire [(C_S_AXI_DATA_WIDTH/8)-1:0] s_axi_ctrl_wstrb,
    input  wire                          s_axi_ctrl_wvalid,
    output wire                          s_axi_ctrl_wready,
    output wire [1:0]                    s_axi_ctrl_bresp,
    output wire                         s_axi_ctrl_bvalid,
    input  wire                          s_axi_ctrl_bready,
    input  wire [C_S_AXI_ADDR_WIDTH-1:0] s_axi_ctrl_araddr,
    input  wire [2:0]                    s_axi_ctrl_arprot,
    input  wire                          s_axi_ctrl_arvalid,
    output wire                          s_axi_ctrl_arready,
    output wire [C_S_AXI_DATA_WIDTH-1:0] s_axi_ctrl_rdata,
    output wire [1:0]                    s_axi_ctrl_rresp,
    output wire                          s_axi_ctrl_rvalid,
    input  wire                          s_axi_ctrl_rready,

    // BRAM IMEM
    output wire        bram_imem_clk,
    output wire        bram_imem_rst,
    output wire        bram_imem_en,
    output wire [3:0]  bram_imem_we,
    output wire [31:0] bram_imem_addr,
    output wire [31:0] bram_imem_din,
    input  wire [31:0] bram_imem_dout,

    // BRAM DMEM
    output wire        bram_dmem_clk,
    output wire        bram_dmem_rst,
    output wire        bram_dmem_en,
    output wire [3:0]  bram_dmem_we,
    output wire [31:0] bram_dmem_addr,
    output wire [31:0] bram_dmem_din,
    input  wire [31:0] bram_dmem_dout,

    // AXI4 Master to PS DDR
    output wire [AXI_ADDR_WIDTH-1:0]     m_axi_ddr_awaddr,
    output wire [2:0]                    m_axi_ddr_awprot,
    output wire [7:0]                    m_axi_ddr_awlen,
    output wire [2:0]                    m_axi_ddr_awsize,
    output wire [1:0]                    m_axi_ddr_awburst,
    output wire                          m_axi_ddr_awvalid,
    input  wire                          m_axi_ddr_awready,
    output wire [AXI_DATA_WIDTH-1:0]     m_axi_ddr_wdata,
    output wire [(AXI_DATA_WIDTH/8)-1:0] m_axi_ddr_wstrb,
    output wire                          m_axi_ddr_wlast,
    output wire                          m_axi_ddr_wvalid,
    input  wire                          m_axi_ddr_wready,
    input  wire [1:0]                    m_axi_ddr_bresp,
    input  wire                          m_axi_ddr_bvalid,
    output wire                          m_axi_ddr_bready,
    output wire [AXI_ADDR_WIDTH-1:0]     m_axi_ddr_araddr,
    output wire [2:0]                    m_axi_ddr_arprot,
    output wire [7:0]                    m_axi_ddr_arlen,
    output wire [2:0]                    m_axi_ddr_arsize,
    output wire [1:0]                    m_axi_ddr_arburst,
    output wire                          m_axi_ddr_arvalid,
    input  wire                          m_axi_ddr_arready,
    input  wire [AXI_DATA_WIDTH-1:0]     m_axi_ddr_rdata,
    input  wire [1:0]                    m_axi_ddr_rresp,
    input  wire                          m_axi_ddr_rlast,
    input  wire                          m_axi_ddr_rvalid,
    output wire                          m_axi_ddr_rready
);

    // Instantiate the SystemVerilog Wrapper
    riscv_zynq_wrapper #(
        .ADDR_WIDTH(ADDR_WIDTH),
        .AXI_ADDR_WIDTH(AXI_ADDR_WIDTH),
        .AXI_DATA_WIDTH(AXI_DATA_WIDTH),
        .C_S_AXI_DATA_WIDTH(C_S_AXI_DATA_WIDTH),
        .C_S_AXI_ADDR_WIDTH(C_S_AXI_ADDR_WIDTH)
    ) sv_inst (
        .clk(clk),
        .aresetn(aresetn),
        .s_axi_ctrl_awaddr(s_axi_ctrl_awaddr),
        .s_axi_ctrl_awprot(s_axi_ctrl_awprot),
        .s_axi_ctrl_awvalid(s_axi_ctrl_awvalid),
        .s_axi_ctrl_awready(s_axi_ctrl_awready),
        .s_axi_ctrl_wdata(s_axi_ctrl_wdata),
        .s_axi_ctrl_wstrb(s_axi_ctrl_wstrb),
        .s_axi_ctrl_wvalid(s_axi_ctrl_wvalid),
        .s_axi_ctrl_wready(s_axi_ctrl_wready),
        .s_axi_ctrl_bresp(s_axi_ctrl_bresp),
        .s_axi_ctrl_bvalid(s_axi_ctrl_bvalid),
        .s_axi_ctrl_bready(s_axi_ctrl_bready),
        .s_axi_ctrl_araddr(s_axi_ctrl_araddr),
        .s_axi_ctrl_arprot(s_axi_ctrl_arprot),
        .s_axi_ctrl_arvalid(s_axi_ctrl_arvalid),
        .s_axi_ctrl_arready(s_axi_ctrl_arready),
        .s_axi_ctrl_rdata(s_axi_ctrl_rdata),
        .s_axi_ctrl_rresp(s_axi_ctrl_rresp),
        .s_axi_ctrl_rvalid(s_axi_ctrl_rvalid),
        .s_axi_ctrl_rready(s_axi_ctrl_rready),
        .bram_imem_clk(bram_imem_clk),
        .bram_imem_rst(bram_imem_rst),
        .bram_imem_en(bram_imem_en),
        .bram_imem_we(bram_imem_we),
        .bram_imem_addr(bram_imem_addr),
        .bram_imem_din(bram_imem_din),
        .bram_imem_dout(bram_imem_dout),
        .bram_dmem_clk(bram_dmem_clk),
        .bram_dmem_rst(bram_dmem_rst),
        .bram_dmem_en(bram_dmem_en),
        .bram_dmem_we(bram_dmem_we),
        .bram_dmem_addr(bram_dmem_addr),
        .bram_dmem_din(bram_dmem_din),
        .bram_dmem_dout(bram_dmem_dout),
        .m_axi_ddr_awaddr(m_axi_ddr_awaddr),
        .m_axi_ddr_awprot(m_axi_ddr_awprot),
        .m_axi_ddr_awlen(m_axi_ddr_awlen),
        .m_axi_ddr_awsize(m_axi_ddr_awsize),
        .m_axi_ddr_awburst(m_axi_ddr_awburst),
        .m_axi_ddr_awvalid(m_axi_ddr_awvalid),
        .m_axi_ddr_awready(m_axi_ddr_awready),
        .m_axi_ddr_wdata(m_axi_ddr_wdata),
        .m_axi_ddr_wstrb(m_axi_ddr_wstrb),
        .m_axi_ddr_wlast(m_axi_ddr_wlast),
        .m_axi_ddr_wvalid(m_axi_ddr_wvalid),
        .m_axi_ddr_wready(m_axi_ddr_wready),
        .m_axi_ddr_bresp(m_axi_ddr_bresp),
        .m_axi_ddr_bvalid(m_axi_ddr_bvalid),
        .m_axi_ddr_bready(m_axi_ddr_bready),
        .m_axi_ddr_araddr(m_axi_ddr_araddr),
        .m_axi_ddr_arprot(m_axi_ddr_arprot),
        .m_axi_ddr_arlen(m_axi_ddr_arlen),
        .m_axi_ddr_arsize(m_axi_ddr_arsize),
        .m_axi_ddr_arburst(m_axi_ddr_arburst),
        .m_axi_ddr_arvalid(m_axi_ddr_arvalid),
        .m_axi_ddr_arready(m_axi_ddr_arready),
        .m_axi_ddr_rdata(m_axi_ddr_rdata),
        .m_axi_ddr_rresp(m_axi_ddr_rresp),
        .m_axi_ddr_rlast(m_axi_ddr_rlast),
        .m_axi_ddr_rvalid(m_axi_ddr_rvalid),
        .m_axi_ddr_rready(m_axi_ddr_rready)
    );

endmodule
