#ifndef SHARED_MEM_H
#define SHARED_MEM_H

#include <stdint.h>

/*
 * Direct-BRAM mailbox layout as seen by the RV32IM core.
 *
 * The core has separate IMEM and DMEM ports, so low DMEM offsets are safe for
 * result/status words.
 */
#define MAILBOX_BASE            0x000U
#define MAILBOX_INPUT0_OFFSET   0x004U
#define MAILBOX_INPUT1_OFFSET   0x008U
#define MAILBOX_RESULT_OFFSET   0x00CU
#define MAILBOX_STATUS_OFFSET   0x010U
#define MAILBOX_FAIL_OFFSET     0x014U
#define MAILBOX_EXPECTED_OFFSET 0x018U
#define MAILBOX_DIAG_OFFSET     0x020U

#define MAILBOX_RESERVED_BYTES  0x100U
#define MAILBOX_POLL_BYTES      0x20U

#define STATUS_IDLE             0x00000000U
#define STATUS_DONE             0xCAFECAFEU
#define STATUS_TEST_DONE        0xABCDE000U

/* RV32IM core view */
#define MAILBOX_STATUS_ADDR     ((volatile uint32_t *)(MAILBOX_BASE + MAILBOX_STATUS_OFFSET))
#define MAILBOX_INPUT0_ADDR     ((volatile uint32_t *)(MAILBOX_BASE + MAILBOX_INPUT0_OFFSET))
#define MAILBOX_INPUT1_ADDR     ((volatile uint32_t *)(MAILBOX_BASE + MAILBOX_INPUT1_OFFSET))
#define MAILBOX_RESULT_ADDR     ((volatile uint32_t *)(MAILBOX_BASE + MAILBOX_RESULT_OFFSET))
#define MAILBOX_FAIL_COUNT_ADDR ((volatile uint32_t *)(MAILBOX_BASE + MAILBOX_FAIL_OFFSET))
#define MAILBOX_EXPECTED_ADDR   ((volatile uint32_t *)(MAILBOX_BASE + MAILBOX_EXPECTED_OFFSET))
#define MAILBOX_DIAG_BASE       (MAILBOX_BASE + MAILBOX_DIAG_OFFSET)

/* ARM view */
#define DMEM_STATUS_OFFSET      (MAILBOX_BASE + MAILBOX_STATUS_OFFSET)
#define DMEM_INPUT0_OFFSET      (MAILBOX_BASE + MAILBOX_INPUT0_OFFSET)
#define DMEM_INPUT1_OFFSET      (MAILBOX_BASE + MAILBOX_INPUT1_OFFSET)
#define DMEM_RESULT_OFFSET      (MAILBOX_BASE + MAILBOX_RESULT_OFFSET)
#define DMEM_FAIL_OFFSET        (MAILBOX_BASE + MAILBOX_FAIL_OFFSET)
#define DMEM_EXPECTED_OFFSET    (MAILBOX_BASE + MAILBOX_EXPECTED_OFFSET)
#define DMEM_DIAG_OFFSET        (MAILBOX_BASE + MAILBOX_DIAG_OFFSET)

#define AXI_BRAM_STATUS_OFFSET  DMEM_STATUS_OFFSET
#define AXI_BRAM_INPUT0_OFFSET  DMEM_INPUT0_OFFSET
#define AXI_BRAM_INPUT1_OFFSET  DMEM_INPUT1_OFFSET
#define AXI_BRAM_RESULT_OFFSET  DMEM_RESULT_OFFSET

#endif
